### ISSUE TITLE
Fallback path for sub directories does not work with release 0.0.2

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin-fileserver#37]
Hey 👋🏻 ,

I was playing with `spin-fileserver` today. And it happens that `index.html` for sub-directories is not resolved as mentioned in #30 and actually fixed as part of #31 

I updated my local `spin` CLI and all the templates using `spin templates upgrade` so I ended up with having `spin` CLI in `spin 1.4.1 (e0bd911 2023-07-12)` 

When creating a new app using `spin new` and selecting the _static-fileserver (Serves static files from an asset directory)_ template, I end up with the following `Spin.toml`:

```toml
spin_manifest_version = "1"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""
name = "app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "app"
files = [ { source = "assets", destination = "/" } ]
[component.trigger]
route = "/static/..."
```
From here, I updated my `Spin.toml` (I changed `route`, `files::sources`, and added the `FALLBACK_PATH` env var), making my `Spin.toml` looks like this:

```toml
spin_manifest_version = "1"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""
name = "app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "app"
files = [ { source = "public", destination = "/" } ]
environment = { FALLBACK_PATH = "index.html" }
[component.trigger]
route = "/..."
```

## Actual behavior

After starting the application using `spin up` I can browse `http://localhost:3000` which correctly returns `http://localhost:3000/index.html`. 

However, when I try to access `http://localhost:3000/foo` (which is a directory containing an `index.html`), I receiver the `index.html` from the root folder and the following is printed to `stdout`:

```console
Cannot find file /foo/. Attempting fallback.
```

## Expected behavior

The static fileserver should return `index.html` from the subfolder.

## Where things get strange

I cloned [fermyon/spin-fileserver](https://github.com/fermyon/spin-fileserver/) (this repository) and compiled it using `make`. Then I replaced the `component::source` and point it to my local version of `spin-fileserver` 

```toml
[[component]]
source = "../../spin-fileserver/target/wasm32-wasi/release/spin_static_fs.wasm"
```

When running this, the `index.html` from the sub-directory `foo` is served correctly. Besides adding some `println!` statements to see how paths were resolved I have not made any changes! (See my `git diff` below)

It looks like something is **broken/wrong with the release** `0.0.2` of the fermyon/spin-fileserver.

<img width="1341" alt="image" src="https://github.com/fermyon/spin-fileserver/assets/357884/d97a7354-b673-4336-9ec8-998408399da2">
